# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Execute conversion script
        run: |
          source venv/bin/activate
          python scripts/convert_notebooks.py

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build

      # Force load v4 of upload-artifact early
      - name: Preload upload-artifact v4
        uses: actions/upload-artifact@v4
        with:
          name: noop
          path: README.md

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site  # Path to your built Jekyll site (change if needed)

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
